export const PRODUCTS_ALL = 'PRODUCTS_ALL';
export const PRODUCTS_ALL_PENDING = 'PRODUCTS_ALL_PENDING';
export const PRODUCTS_ALL_FULFILLED = 'PRODUCTS_ALL_FULFILLED';

export const PRODUCTS_ONE = 'PRODUCTS_ONE';
export const PRODUCTS_ONE_PENDING = 'PRODUCTS_ONE_PENDING';
export const PRODUCTS_ONE_FULFILLED = 'PRODUCTS_ONE_FULFILLED';
