export const PRODUCTS_ALL = 'PRODUCTS_ALL';
export const PRODUCTS_ALL_PENDING = 'PRODUCTS_ALL_PENDING';
export const PRODUCTS_ALL_FULFILLED = 'PRODUCTS_ALL_FULFILLED';
export const PRODUCTS_ALL_REJECTED = 'PRODUCTS_ALL_REJECTED';

export const PRODUCTS_ONE = 'PRODUCTS_ONE';
export const PRODUCTS_ONE_PENDING = 'PRODUCTS_ONE_PENDING';
export const PRODUCTS_ONE_FULFILLED = 'PRODUCTS_ONE_FULFILLED';
export const PRODUCTS_ONE_REJECTED = 'PRODUCTS_ONE_REJECTED';

export const PRODUCTS_ONE_SELECTED = 'PRODUCTS_ONE_SELECTED';
export const PRODUCTS_ONE_SELECTED_PENDING = 'PRODUCTS_ONE_SELECTED_PENDING';
export const PRODUCTS_ONE_SELECTED_FULFILLED = 'PRODUCTS_ONE_SELECTED_FULFILLED';
export const PRODUCTS_ONE_SELECTED_REJECTED = 'PRODUCTS_ONE_SELECTED_REJECTED';

export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';
export const PRODUCT_UPDATE_PENDING = 'PRODUCT_UPDATE_PENDING';
export const PRODUCT_UPDATE_FULFILLED = 'PRODUCT_UPDATE_FULFILLED';
export const PRODUCT_UPDATE_REJECTED = 'PRODUCT_UPDATE_REJECTED';

export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_DELETE_PENDING = 'PRODUCT_DELETE_PENDING';
export const PRODUCT_DELETE_FULFILLED = 'PRODUCT_DELETE_FULFILLED';
export const PRODUCT_DELETE_REJECTED = 'PRODUCT_DELETE_REJECTED';
