export const STORES_ALL = 'STORES_ALL';
export const STORES_ALL_PENDING = 'STORES_ALL_PENDING';
export const STORES_ALL_FULFILLED = 'STORES_ALL_FULFILLED';

export const STORES_ONE = 'STORES_ONE';
export const STORES_ONE_PENDING = 'STORES_ONE_PENDING';
export const STORES_ONE_FULFILLED = 'STORES_ONE_FULFILLED';
