export const STORES_ALL = 'STORES_ALL';
export const STORES_ALL_PENDING = 'STORES_ALL_PENDING';
export const STORES_ALL_FULFILLED = 'STORES_ALL_FULFILLED';
export const STORES_ALL_REJECTED = 'STORES_ALL_REJECTED';

export const STORES_ONE = 'STORES_ONE';
export const STORES_ONE_PENDING = 'STORES_ONE_PENDING';
export const STORES_ONE_FULFILLED = 'STORES_ONE_FULFILLED';
export const STORES_ONE_REJECTED = 'STORES_ONE_REJECTED';

export const STORES_ONE_SELECTED = 'STORES_ONE_SELECTED';

export const STORE_UPDATE = 'STORE_UPDATE';
export const STORE_UPDATE_PENDING = 'STORE_UPDATE_PENDING';
export const STORE_UPDATE_FULFILLED = 'STORE_UPDATE_FULFILLED';
export const STORE_UPDATE_REJECTED = 'STORE_UPDATE_REJECTED';

export const STORE_DELETE = 'STORE_DELETE';
export const STORE_DELETE_PENDING = 'STORE_DELETE_PENDING';
export const STORE_DELETE_FULFILLED = 'STORE_DELETE_FULFILLED';
export const STORE_DELETE_REJECTED = 'STORE_DELETE_REJECTED';
