export const SUBSCRIPTIONS_ALL = 'SUBSCRIPTIONS_ALL';
export const SUBSCRIPTIONS_ALL_PENDING = 'SUBSCRIPTIONS_ALL_PENDING';
export const SUBSCRIPTIONS_ALL_FULFILLED = 'SUBSCRIPTIONS_ALL_FULFILLED';
export const SUBSCRIPTIONS_ALL_REJECTED = 'SUBSCRIPTIONS_ALL_REJECTED';

export const SUBSCRIPTION_ADD = 'SUBSCRIPTION_ADD';
export const SUBSCRIPTION_ADD_PENDING = 'SUBSCRIPTION_ADD_PENDING';
export const SUBSCRIPTION_ADD_FULFILLED = 'SUBSCRIPTION_ADD_FULFILLED';
export const SUBSCRIPTION_ADD_REJECTED = 'SUBSCRIPTION_ADD_REJECTED';

export const SUBSCRIPTION_REMOVE = 'SUBSCRIPTION_REMOVE';
export const SUBSCRIPTION_REMOVE_PENDING = 'SUBSCRIPTION_REMOVE_PENDING';
export const SUBSCRIPTION_REMOVE_FULFILLED = 'SUBSCRIPTION_REMOVE_FULFILLED';
export const SUBSCRIPTION_REMOVE_REJECTED = 'SUBSCRIPTION_REMOVE_REJECTED';
