export const TESTIMONIALS_ALL = 'TESTIMONIALS_ALL';
export const TESTIMONIALS_ALL_PENDING = 'TESTIMONIALS_ALL_PENDING';
export const TESTIMONIALS_ALL_FULFILLED = 'TESTIMONIALS_ALL_FULFILLED';
export const TESTIMONIALS_ALL_REJECTED = 'TESTIMONIALS_ALL_REJECTED';

export const TESTIMONIALS_ONE = 'TESTIMONIALS_ONE';
export const TESTIMONIALS_ONE_PENDING = 'TESTIMONIALS_ONE_PENDING';
export const TESTIMONIALS_ONE_FULFILLED = 'TESTIMONIALS_ONE_FULFILLED';
export const TESTIMONIALS_ONE_REJECTED = 'TESTIMONIALS_ONE_REJECTED';

export const TESTIMONIALS_ONE_SELECTED = 'TESTIMONIALS_ONE_SELECTED';

export const TESTIMONIAL_UPDATE = 'TESTIMONIAL_UPDATE';
export const TESTIMONIAL_UPDATE_PENDING = 'TESTIMONIAL_UPDATE_PENDING';
export const TESTIMONIAL_UPDATE_FULFILLED = 'TESTIMONIAL_UPDATE_FULFILLED';
export const TESTIMONIAL_UPDATE_REJECTED = 'TESTIMONIAL_UPDATE_REJECTED';

export const TESTIMONIAL_DELETE = 'TESTIMONIAL_DELETE';
export const TESTIMONIAL_DELETE_PENDING = 'TESTIMONIAL_DELETE_PENDING';
export const TESTIMONIAL_DELETE_FULFILLED = 'TESTIMONIAL_DELETE_FULFILLED';
export const TESTIMONIAL_DELETE_REJECTED = 'TESTIMONIAL_DELETE_REJECTED';
