export const USERS_ALL = 'USERS_ALL';
export const USERS_ALL_PENDING = 'USERS_ALL_PENDING';
export const USERS_ALL_FULFILLED = 'USERS_ALL_FULFILLED';
export const USERS_ALL_REJECTED = 'USERS_ALL_REJECTED';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_PENDING = 'USER_UPDATE_PENDING';
export const USER_UPDATE_FULFILLED = 'USER_UPDATE_FULFILLED';
export const USER_UPDATE_REJECTED = 'USER_UPDATE_REJECTED';

export const USER_ONE = 'USER_ONE';
export const USER_ONE_PENDING = 'USER_ONE_PENDING';
export const USER_ONE_FULFILLED = 'USER_ONE_FULFILLED';
export const USER_ONE_REJECTED = 'USER_ONE_REJECTED';

export const USER_DELETE = 'USER_DELETE';
export const USER_DELETE_PENDING = 'USER_DELETE_PENDING';
export const USER_DELETE_FULFILLED = 'USER_DELETE_FULFILLED';
export const USER_DELETE_REJECTED = 'USER_DELETE_REJECTED';

export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASSWORD_PENDING = 'USER_CHANGE_PASSWORD_PENDING';
export const USER_CHANGE_PASSWORD_FULFILLED = 'USER_CHANGE_PASSWORD_FULFILLED';
export const USER_CHANGE_PASSWORD_REJECTED = 'USER_CHANGE_PASSWORD_REJECTED';
